### ISSUE TITLE
Feat: webcall actions

### ISSUE THREAD

**Issue by miton18** [linkedin/iris#349]
Hi !

Iris allow lots of actions in its plans steps, like :
- User
- Manager
- Team
- Oncall-Primary
- Oncall-Secondary

It could be useful to have a 'WebCall' action which perform a simple HTTP call.

Why ?
- Some microservices can perfom actions on incident
- Make aggregations of incidents to build globals services status pages
- We can build and update services dependencies trees
- finaly, we can integrate Iris with others services like statuscake, datadog, etc...

**Comment by wleese** [comment]
The actions you mention are actually a single action, implemented in multiple ways. Namely looking up a value ("who's on call?").

What you probably are thinking of are the vendor plugins, which are linked to priorities. Say urgent messages -> call, medium -> chat, low -> email. Additionally it seems you'd not want this as a "step" but as "Incident Tracking". Meaning that regardless of how messages are created and escalations go, there will always be 1 message sent to $channel.

Now interestingly there seems to only be support for doing "Incident Tracking" using the email vendor. I'll be looking into making this more flexible so that any vendor plugin can be used instead - we happen to need the ability to send all alerts to chat rooms as well as the normal alerting workflow.

Once this is in place, all you'd need is a vendor plugin which does your specific http call. You wouldn't be able to make this very generic though - every purpose would need it's own plugin. Or you'd have one big plugin specific to your organization.

**Comment by miton18** [comment]
I understand what you say, I'm not talking about vendors integration :-)
we already code a custom vendor for our internal usage linked to our infra

I speak about that: https://github.com/linkedin/iris/blob/a73b8c8543135b79e2a025db7932ae6e0cb9ef45/src/iris/constants.py

In some steps, it can be interesting to have an action of type "HTTP_REQUEST" which just perform an http call on another API (not necessary a notification ways provider)

**Comment by dwang159** [comment]
That's an interesting generalization of the Iris framework. We've focused on notifications, but adding an HTTP request "contact mode" could work. I think the drawback you might find here is that contact mode destinations (e.g. phone numbers or Slack handles) are defined per-user, so having several webhook locations would be difficult.

I think what @wleese describes is likely a better place for this kind of functionality. This way, you would be able to set the request target per-plan. I believe the framework for incident tracking is fairly general (we had some plans to integrate Jira, which was ultimately pushed into the backlog), so this should be doable via that channel.

**Comment by miton18** [comment]
Ok, thanks for all :-)
