### ISSUE TITLE
Question: Is it possible to use iris without LDAP?

### ISSUE THREAD

**Issue by sankethkatta** [linkedin/iris#394]
I am attempting to setup and try-out Iris for our company's oncall system, however we do not use LDAP for authentication. Is Iris usable without it? I did not see any documentation on authentication in the README.

**Comment by dwang159** [comment]
Iris currently has no built-in credential storage, so it relies on another system to provide this. At LinkedIn, this is LDAP, but it's possible that another system would work as well. As for internal support for auth within Iris; that's unfortunately living in the backlog for now, since LDAP covers a decent chunk of use-cases. Contributions are welcome if you're interested though :)

**Comment by dwang159** [comment]
Iris currently has no built-in credential storage, so it relies on another system to provide this. At LinkedIn, this is LDAP, but it's possible that another system would work as well. As for internal support for auth within Iris; that's unfortunately living in the backlog for now, since LDAP covers a decent chunk of use-cases. Contributions are welcome if you're interested though :)

**Comment by sankethkatta** [comment]
Got it, thanks @dwang159!
