### ISSUE TITLE
Ue postgresql instead of mysql ?

### ISSUE THREAD

**Issue by Ozymandiiaz** [linkedin/iris#406]
Is it possible to use postgresql instead of mysql ?

**Comment by jrgp** [comment]
Theoretically, Iris could be adapted/ported to work with Postgres, but this would be a bit of work:

- All of our SQL queries are hardcoded to with MySQL in mind. For performance reasons, we do not use a database-agnostic ORM. Many of our queries would likely work out of the box on Postgres, but a few are likely dependent on MySQL-specific functionality

- We'd need to find a Postgres db driver that plays nice with gevent, eg written in pure python rather than C.

- We'd need to convert our db schema file from MySQL to Postgres, accounting for differences between the two: https://github.com/linkedin/iris/blob/master/db/schema_0.sql
