### ISSUE TITLE
where to customize email message templates?

### ISSUE THREAD

**Issue by jensenja** [linkedin/iris#413]
Hi,

I'd like to remove the incident ID from email message subject headers - where can I do this in the code?

Thanks!

edit: Happy 4th!

**Comment by dwang159** [comment]
This one was surprisingly tricky to find: https://github.com/linkedin/iris/blob/master/src/iris/sender/cache.py#L115. I'm not a huge fan of where it ended up. One thing to note; users may have difficulty claiming via text/email replies without the message ID, since "claim last" may not be sufficient in some cases. I believe this is why we force the message id to be included in a template. It looks like you can get rid of the ID in the subject by putting it somewhere in the body, though, without any need for code changes.
