### ISSUE TITLE
How to configure delay between incident and alerting ?

### ISSUE THREAD

**Issue by Ozymandiiaz** [linkedin/iris#423]
How to configure delay between incident and alerting ?

**Comment by dwang159** [comment]
Incidents are created in the Iris API, and the Iris sender is responsible for sending messages associated with those incidents. The delay you're seeing is because Iris sender is spinning on a 1-minute loop. At most, this delay should be 1-minute long. To change this around, you can look at https://github.com/linkedin/iris/blob/master/src/iris/bin/sender.py#L1540, which is where this sleep time is configured. Having Iris sender sleep for less time may use more resources, since the incident escalation and aggregation logic will be run more often. I'm not sure whether an assumption of a 1-minute sleep is built into the system, but you can try it out and see how it goes.
